E-commerce-23TH0024/Models/Order/ChiTietDonHang.cs
namespace E_commerce_23TH0024.Models.Order;

public partial class ChiTietDonHang
{
    public int Id { get; set; }

    public int IdDonHang { get; set; }

    public int IdSanPham { get; set; }

    public int SoLuong { get; set; }

    public decimal DonGia { get; set; }

    public decimal DiscountApplied { get; set; }

    public virtual DonHang DonHang { get; set; } = null!;
}

E-commerce-23TH0024/Models/Order/CustomerType.cs
using System;
using System.Collections.Generic;

namespace E_commerce_23TH0024.Models.Order;

public partial class CustomerType
{
    public int Id { get; set; }

    public string? CustomerTypeName { get; set; }

    public virtual ICollection<DiscountRule> DiscountRules { get; set; } = new List<DiscountRule>();

    public virtual ICollection<KhachHang> KhachHangs { get; set; } = new List<KhachHang>();
}

E-commerce-23TH0024/Models/Order/DeliveryMethod.cs
using System;
using System.Collections.Generic;

namespace E_commerce_23TH0024.Models.Order;

public partial class DeliveryMethod
{
    public int Id { get; set; }

    public string? MethodName { get; set; }

    public string? Description { get; set; }

    public decimal? Cost { get; set; }

    public string? DeliveryTime { get; set; }

    public bool ActiveStatus { get; set; }

    public virtual ICollection<DonHang> DonHangs { get; set; } = new List<DonHang>();

    public virtual ICollection<ShippingRate> ShippingRates { get; set; } = new List<ShippingRate>();
}

E-commerce-23TH0024/Models/Order/DiscountRule.cs
namespace E_commerce_23TH0024.Models.Order;

public partial class DiscountRule
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Discount_Type { get; set; }

    public string? Description { get; set; }

    public decimal MinTotalPrice { get; set; }

    public decimal DiscountAmount { get; set; }

    public int DiscountPercent { get; set; }

    public int? IdLoaiSanPham { get; set; }

    public int? IdCustomerType { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? Created_at { get; set; }

    public virtual CustomerType? CustomerType { get; set; }
}

E-commerce-23TH0024/Models/Order/DonHang.cs
namespace E_commerce_23TH0024.Models.Order;

public partial class DonHang
{
    public int Id { get; set; }

    public DateTime? NgayDatHang { get; set; }

    public DateTime? NgayGiaoHang { get; set; }

    public int? IdKhachHang { get; set; }

    public int? IdNhanVienGiao { get; set; }

    public int? IdNhanVienDuyet { get; set; }

    public int? TinhTrang { get; set; } // 0: chua duyet, 1: da duyet
    public decimal VAT { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal ShippingFee { get; set; }

    public int? IdDeliveryMethod { get; set; }

    public decimal TotalProductAmount { get; set; }

    public int? IdDiscountRule { get; set; }

    public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; } = new List<ChiTietDonHang>();
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
    public virtual DiscountRule? DiscountRule { get; set; }

    public virtual KhachHang? KhachHang { get; set; }

    //[ForeignKey("IdNhanVienGiao")]
    //public virtual NhanVien? NhanVienGiao { get; set; }

    //[ForeignKey("IdNhanVienDuyet")]
    //public virtual NhanVien? NhanVienDuyet { get; set; }

    public virtual DeliveryMethod? DeliveryMethod { get; set; }
}

E-commerce-23TH0024/Models/Order/KhachHang.cs
using E_commerce_23TH0024.Models.Identity;
using E_commerce_23TH0024.Models.Location;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace E_commerce_23TH0024.Models.Order;

public partial class KhachHang
{
    public int Id { get; set; }

    public string? HoTen { get; set; }

    public string? IdAspNetUsers { get; set; }

    public int? IdCustomerType { get; set; }

    public string? SoDienThoai { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public int? IdCity { get; set; }

    public int? IdDistrict { get; set; }

    public int? IdWard { get; set; }

    public string? DiaChi { get; set; }

    //public virtual City? City { get; set; }

    public virtual CustomerType? CustomerType { get; set; }

    //public virtual District? District { get; set; }

    public virtual ICollection<DonHang> DonHangs { get; set; } = new List<DonHang>();
    [NotMapped]
    public virtual ApplicationUser? AspNetUser { get; set; }
    //public virtual Ward? Ward { get; set; }
}

E-commerce-23TH0024/Models/Order/Payment.cs
namespace E_commerce_23TH0024.Models.Order
{
    public class Payment
    {
        public int Id { get; set; }
        public int IdDonHang { get; set; }
        public decimal Amount { get; set; }
        public int PaymentStatus { get; set; }
        public int PaymentMethod { get; set; }
        public DateTime PaymentDate { get; set; }
        public string? GatewayTransactionId { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}

E-commerce-23TH0024/Models/Order/ShippingRate.cs
using E_commerce_23TH0024.Models.Location;
using System;
using System.Collections.Generic;

namespace E_commerce_23TH0024.Models.Order;

public partial class ShippingRate
{
    public int Id { get; set; }

    public int? IdDeliveryMethod { get; set; }

    public double? FromDistance { get; set; }

    public double? ToDistance { get; set; }

    public decimal FixedPrice { get; set; }

    public decimal PricePerKm { get; set; }

    public int? IdCity { get; set; }

    public decimal? WeightLitmit { get; set; }

    public DateTime? CreateAt { get; set; }

    //public virtual City? City { get; set; }

    public virtual DeliveryMethod? DeliveryMethod { get; set; }
}

E-commerce-23TH0024/Areas/Admin/Controllers/DonHangs_23TH0024Controller.cs
using System.Data;
using E_commerce_23TH0024.Models;
using E_commerce_23TH0024.Data;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using E_commerce_23TH0024.Areas.Admin.Controllers;
using E_commerce_23TH0024.Models.Ecommerce;
using E_commerce_23TH0024.Service;
using E_commerce_23TH0024.Lib.Enums;
using E_commerce_23TH0024.Lib;
using System.Security.Claims;
using E_commerce_23TH0024.Models.Order;
using E_commerce_23TH0024.ViewModels;

namespace E_commerce_23TH0024.Areas.AdminControllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DonHangs_23TH0024Controller : Controller
    {
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly DonHangService _service;
        private readonly ApplicationDbContext db;
        private readonly Shipping_23TH0024Controller _shipping;
        public DonHangs_23TH0024Controller(ApplicationDbContext context, IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
            db = context;
            _shipping = new Shipping_23TH0024Controller(db);
            _service = new DonHangService(db);
        }
        public ActionResult OrderListForCustomer()
        {
            string UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var kh = db.KhachHang.SingleOrDefault(x => x.IdAspNetUsers == UserID);
                if (kh != null)
                {
                    var donhangs = db.DonHangs.FromSqlRaw("EXEC GetDonHangs @UserID, @SoDienThoai, @Email",
              new SqlParameter("@UserID", (object)UserID ?? DBNull.Value),
              new SqlParameter("@SoDienThoai", DBNull.Value),
              new SqlParameter("@Email", DBNull.Value)
              ).ToList();
                    if (donhangs.Count == 0)
                        ViewBag.TB = "Không có thông tin tìm kiếm.";
                    return View(donhangs);
                }
                else
                {
                    ViewBag.TB = "Không tồn tài khách hàng";
                }
              
            return View();
        }
        private Cart GetCart()
        {
            var cartCookie = _contextAccessor.HttpContext.Request.Cookies["Cart"];
            if (cartCookie != null)
            {
                var cartData = cartCookie;
                var cart = JsonConvert.DeserializeObject<Cart>(cartData);
                foreach (var item in cart.Items)
                {
                    var product = db.SanPham.SingleOrDefault(x => x.Id == item.Id);
                    if (product != null)
                    {
                        item.Anh = product.Anh;
                        item.TenSP = product.TenSP;
                        item.DonGia = product.DonGia.Value;
                        item.LoaiSanPham = product.LoaiSanPham;
                    }
                }
                return cart;
            }
            return new Cart();
        }
        public decimal CalculateShippingFee(int shippingMethod)
        {
            double lat = 12.2797806597436;
            double lng = 109.199100989104;
            string UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var kh = db.KhachHang.SingleOrDefault(x => x.IdAspNetUsers.ToString() == UserID);
            if (kh == null)
            {
                return 0;
            }
            double distance = _shipping.CalculateDistance((double)kh.Latitude, (double)kh.Longitude, lat, lng);
            
            var fees = db.ShippingRates.Where(x =>  x.IdDeliveryMethod.HasValue && x.IdDeliveryMethod.Value == shippingMethod
                                                        && x.FromDistance.HasValue && x.FromDistance.Value <= distance
                                                        && (x.ToDistance.HasValue ? x.ToDistance.Value >= distance : true)
                                                      );
            if (fees != null && fees.Any())
            {
                return Math.Round(fees.Min(x => x.FixedPrice + x.PricePerKm * (decimal)distance), 2);
            }
            return 0;
        }
        [AllowAnonymous]
        public async Task<ActionResult> Order()
        {
            DonHang donHang = new DonHang();
            var cart = GetCart();
            if (cart.Items.Count == 0)
            {
                TempData["Message"] = "Giỏ hàng của bạn đang trống.";
                return RedirectToAction("Index");
            }
            if (!cart.Total.HasValue)
            {
                TempData["Message"] = "Không tính được tổng tiền sản phẩm";
                return RedirectToAction("Index");
            }

            donHang.TotalProductAmount =cart.Total.Value;

            var DeliveryMethods = db.DeliveryMethods.Where(x => x.ActiveStatus == true);
            ViewBag.shippingMethod = new SelectList(DeliveryMethods, "ShippingMethodID", "MethodName");
            if (User.Identity.IsAuthenticated && User.IsInRole("khachhang"))
            {
                var UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var khachhang = db.KhachHang.SingleOrDefault(x => x.IdAspNetUsers.ToString() == UserID);
                if (khachhang == null)
                {
                    //return RedirectToAction("Login", "Account");
                }
                donHang.KhachHang = khachhang;
                if (DeliveryMethods.Any())
                {
                    donHang.ShippingFee = CalculateShippingFee(DeliveryMethods.First().Id);
                    donHang.TotalAmount = donHang.TotalProductAmount + donHang.ShippingFee;
                }
                else
                {
                    donHang.ShippingFee = 0;
                    donHang.TotalAmount = donHang.TotalProductAmount;
                }
            }
            return View(donHang);
        }

        
        [HttpPost]
        public async Task<ActionResult> Order(int MaKH, int shippingMethod)
        {
            DonHang donHang = new DonHang();
            var khachhang = db.KhachHang.SingleOrDefault(x => x.Id == MaKH);
            try
            {
                donHang.NgayDatHang = DateTime.Now;
                donHang.IdKhachHang = MaKH;
                donHang.IdDeliveryMethod = shippingMethod;
                List<CartItem> cartItems = GetCart().Items;
                decimal Total = 0;
                foreach (var item in cartItems)
                {
                    var chiTietDonHang = new ChiTietDonHang
                    {
                        IdSanPham = item.Id,
                        SoLuong = item.SoLuong,
                        DonGia = item.DonGia.Value,
                        //DiscountApplied = item.DiscountMax()
                    };
                    donHang.ChiTietDonHangs.Add(chiTietDonHang);
                    if (chiTietDonHang.DiscountApplied > 0)
                    {
                        Total += chiTietDonHang.SoLuong * (chiTietDonHang.DonGia - chiTietDonHang.DiscountApplied);
                    }
                    else
                    {
                        Total += chiTietDonHang.SoLuong * chiTietDonHang.DonGia;
                    }
                    
                }

                donHang.ShippingFee = CalculateShippingFee(shippingMethod);
                donHang.TotalProductAmount = Total;
                donHang.TotalAmount = Total + donHang.VAT + donHang.ShippingFee;
                db.DonHangs.Add(donHang);
                await db.SaveChangesAsync();

                //return RedirectToAction("Checkout", new { id = donHang.SoHD });
            }
            catch (Exception ex) { 
                Console.WriteLine(ex.Message);
            }
            ViewBag.shippingMethod = new SelectList(db.DeliveryMethods, "ShippingMethodID", "MethodName", shippingMethod);
            donHang.KhachHang = khachhang;
            return View(donHang);
        }
       
        public ActionResult Checkout(int id)
        {
            var donHang = db.DonHangs.Include(d => d.ChiTietDonHangs).FirstOrDefault(d => d.Id == id);
            if (donHang == null)
            {
                return NotFound();
            }
            return View(donHang);
        }
        
        public ActionResult Index()
        {
            var donHangs = _service.GetDonHangs();
            return View(donHangs);
        }

       
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }
            DonHangViewModel donHang = _service.GetDonHang(id.Value);
            if (donHang == null)
            {
                return NotFound();
            }
            return View(donHang);
        }

        
        public ActionResult Create()
        {
            ViewBag.MaKH = new SelectList(db.KhachHang, "IdKhachHang", "HoTen");
            ViewBag.MaNVDuyet = new SelectList(db.NhanVien, "IdNhanVien", "HoTen");
            ViewBag.MaNVGH = new SelectList(db.NhanVien, "IdNhanVien", "HoTen");
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,NgayDatHang,NgayGiaoHang,IdKhachHang,IdNhanVienDuyet,IdNhanVienGiao,TinhTrang")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.DonHangs.Add(donHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKH = new SelectList(db.KhachHang, "MaKH", "HoTen", donHang.IdKhachHang);
            ViewBag.MaNVDuyet = new SelectList(db.NhanVien, "MaNV", "HoTen", donHang.IdNhanVienDuyet);
            ViewBag.MaNVGH = new SelectList(db.NhanVien, "MaNV", "HoTen", donHang.IdNhanVienGiao);

E-commerce-23TH0024/Views/DonHangs_23TH0024/Checkout.cshtml
@using E_commerce_23TH0024.Models.Ecommerce
@using E_commerce_23TH0024.Models.Order
@using E_commerce_23TH0024.ViewModels
@model DonHangViewModel
@{
    ViewBag.Title = "Thanh toán";
}
<div class="banner">
    <div class="banner-overlay"></div>
    <div class="banner-content">
        <div class="container">
            <h1>Thanh toán</h1>
        </div>

    </div>
</div>
<div class="container">
    <h4 class="mt-3 mb-3 alert-success">Xác Nhận Đơn Hàng Thành Công!</h4>

    <div class="order-details">
        <h4 class="title">Thông Tin Đơn Hàng:</h4>
        @if(Model != null){
            decimal TotalUnit = Model.ChiTietDonHangs.Sum(x => x.DonGia * x.SoLuong);
            <table>
                <tr>
                    <th>Sản phẩm</th>
                    <th>Số lượng</th>
                    <th>Giá</th>
                </tr>
                @if (Model.ChiTietDonHangVM != null)
                    {
                        foreach (var item in Model.ChiTietDonHangVM)
                        {
                            <tr>
                                <td>@item.SanPham.TenSP</td>
                                <td>@item.SoLuong</td>
                                <td>
                                    <span class="old-price">@Helper.money(item.DonGia)</span>
                                    <span style="color:red;">@Helper.money(item.DonGia - item.DiscountApplied)</span>
                                </td>
                            </tr>
                        }
                }
            
            </table>
        <hr />
        <p class=""><b>Tổng tiền sản phẩm: </b>@Helper.money(Model.TotalProductAmount)</p>
        <p class=""><b>VAT:</b> @Model.VAT</p>
        <p class=""><b>Phí vận chuyển: </b>@Helper.money(Model.ShippingFee)</p>
        <p class="total-price"><b>Tổng cộng:</b> @Helper.money(Model.TotalAmount)</p>
        
        <p style="color:green;">Bạn đã tiết kiệm được @Helper.money(TotalUnit - Model.TotalProductAmount)</p>
        }
        
    </div>

    <div class="payment-method">
        <h4 class="title">Phương Thức Thanh Toán:</h4>
         
        <ul>
            <li><strong>Ví điện tử (Momo, ZaloPay, VNPAY, etc.):</strong> 
            <div class="body-content">
                <img src="@ViewBag.QRCodeImage" alt="QR MoMo" style="width: 300px;" />
                <p>Hoặc <a href="@ViewBag.MoMoDeepLink">mở app MoMo</a></p>
            </div>
            </li>
            <li><strong>Thanh toán qua QR Code:</strong> Quét mã QR để thanh toán nhanh chóng qua các nền tảng thanh toán trực tuyến.
                <div class="body-content" style="display:none">
                    <img src="@ViewBag.VietQrCode" alt="QR MoMo" style="width: 300px;" />
                </div>    
            </li>
            <li>
                <strong>Chuyển khoản ngân hàng:</strong> Chuyển khoản trực tiếp vào tài khoản ngân hàng của chúng tôi.
                <div class="body-content" style="display:none;"></div>
            </li>
            <li><strong>Thanh toán khi nhận hàng (COD):</strong> Bạn thanh toán tiền mặt khi nhận hàng.</li>
        </ul>
    </div>

</div>

E-commerce-23TH0024/Views/DonHangs_23TH0024/Create.cshtml
@using E_commerce_23TH0024.Models.Ecommerce
@using E_commerce_23TH0024.Models.Order
@model DonHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DonHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NgayDatHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDatHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDatHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayGiaoHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiaoHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGiaoHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdKhachHang, "IdKhachHang", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdKhachHang", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdKhachHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdNhanVienDuyet, "IdNhanVienDuyet", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdNhanVienDuyet", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdNhanVienDuyet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdNhanVienGiao, "IdNhanVienGiao", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdNhanVienGiao", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdNhanVienGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinhTrang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TinhTrang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TinhTrang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

E-commerce-23TH0024/Views/DonHangs_23TH0024/Order.cshtml
@using E_commerce_23TH0024.Models.Ecommerce
@using E_commerce_23TH0024.Models.Order
@model DonHang
@{
    ViewBag.Title = "Đặt hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string diachi = (Model != null && Model.KhachHang != null) ? Model.KhachHang.DiaChi : "";
}
<div class="banner">
    <div class="banner-overlay"></div>
    <div class="banner-content">
        <div class="container">
            <h1>Đặt hàng</h1>
        </div>

    </div>
</div>
<div class="container">
    @using (Html.BeginForm())
    {
        @*@Html.AntiForgeryToken()*@
        <div class="row">
            <div class="col-md-6">
                <div class="cart-summary">
                    <h4>Thông tin đặt hàng</h4>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("khachhang"))
                    {
                        @Html.Hidden("Id", Model.KhachHang.Id)
                        <div class="form-group">
                            @Html.DisplayName("Họ tên")
                            @Html.TextBoxFor(x => x.KhachHang.HoTen, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                        <div class="form-group">
                            @Html.DisplayName("Email")
                            @Html.TextBoxFor(x => x.KhachHang.AspNetUser.Email, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                        <div class="form-group">
                            @Html.DisplayName("Điện thoại")
                            @Html.TextBoxFor(x => x.KhachHang.SoDienThoai, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                        if (!string.IsNullOrEmpty(Model.KhachHang.DiaChi))
                        {
                            <div class="form-group">
                                @Html.DisplayName("Địa chỉ")
                                @Html.TextBoxFor(x => x.KhachHang.DiaChi, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        }
                        else
                        {
                                <p>Hãy cập nhật địa chỉ giao hàng</p>
                        }
                    }
                    else
                    {
                        <div>
                            Vui lòng <a href='@Url.Action("Login", "Account")'>đăng nhập</a> tài khoản khách hàng để tiếp tục đặt hàng
                            <p>Nếu bạn chưa có tài khoản. Hãy <a href='@Url.Action("Register", "Account")'>Đăng ký</a></p>
                        </div>
                        <div class="form-group">
                            @Html.DisplayName("Điện thoại")
                            @Html.TextBox("SoDienThoai", null, new { @class = "form-control", @required = "required" })
                        </div>
                        <div class="form-group">
                            @Html.DisplayName("Địa chỉ")
                            @Html.TextBox("DiaChi", null, new { @class = "form-control", @required = "required" })
                        </div>
                    }

                </div>
            </div>
            <div class="col-md-6">
                <div class="cart-summary">
                    <label>Phương thức vận chuyển</label>
                    @Html.DropDownList("shippingMethod", null, htmlAttributes: new { @class = "form-control" })
                </div>
                <div class="cart-summary">
                    <h4>Thông tin đơn hàng</h4>
                    <div class="cart-item">
                        <label>Tổng tiền</label>
                        <span>@Helper.money(Model.TotalProductAmount)</span>
                    </div>
                    <div class="cart-item">
                        <label>VAT</label>
                        <span></span>
                    </div>
                    <div class="cart-item">
                        <label>Phí vận chuyển</label>
                        <span id="shippingFee">@Helper.money(Model.ShippingFee)</span>
                    </div>
                    <div class="cart-item total">
                        <label>Thành tiền</label>
                        <span>@Helper.money(Model.TotalAmount)</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex mb-3" style=" justify-content: right;">
            <input type="submit" value="Đặt hàng" class="btn btn-default btn-primary" />
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        $('#shippingMethod').change(function () {
        $('#loading').show();
        var shippingMethodValue = $(this).val();
        if (shippingMethodValue) {
            $.ajax({
                url: '@Url.Action("CalculateShippingFee", "DonHangs_23TH0024")',
                type: 'GET',
                data: {
                    shippingMethod: shippingMethodValue
                },
                success: function (response) {
                    if (response.success === true) {
                        $('#shippingFee').text(response.shippingFee);
                        $('.total span').text(response.Total);
                    } else {
                        alert(response.message);
                    }
                },
                error: function () {
                    alert('Có lỗi xảy ra khi tính phí vận chuyển.');
                },
                complete: function () {
                    $('#loading').hide();
                }
            });
        }
    });
});
</script>