E-commerce-23TH0024/Controllers/Cart_23TH0024Controller.cs
using E_commerce_23TH0024.Models;
using E_commerce_23TH0024.Data;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc;

namespace E_commerce_23TH0024.Controllers
{
    public class Cart_23TH0024Controller : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IHttpContextAccessor _contextAccessor;
        public Cart_23TH0024Controller(ApplicationDbContext context, IHttpContextAccessor contextAccessor)
        {
            db = context;
            _contextAccessor = contextAccessor;
        }
        public ActionResult Index()
        {
            Cart cart = GetCart();
            foreach (var item in cart.Items) { 
                var product = db.SanPham.SingleOrDefault(x => x.Id == item.Id);
                if (product != null)
                {
                    item.Anh = product.Anh;
                    item.TenSP = product.TenSP;
                    item.DonGia = product.DonGia.Value;
                    item.LoaiSanPham = product.LoaiSanPham;
                }
            }
            return View(cart);
        }
        private Cart GetCart()
        {
            var cartCookie = _contextAccessor.HttpContext?.Request.Cookies["Cart"];

            if (cartCookie == null)
            {
                return new Cart();
            }
                var cartData = cartCookie;
            try
            {
                var cart = JsonConvert.DeserializeObject<Cart>(cartData);
                if (cart == null)
                {
                    return new Cart();
                }
                return cart;
            }
            catch (JsonException ex)
            {
                return new Cart();
            }
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult AddToCart(int productId, int quantity)
        {
            var product = db.SanPham.FirstOrDefault(p => p.Id == productId);

            if (product != null)
            {
                if (!product.DonGia.HasValue)
                {
                    return Json(new { success = false, responseText = "Sản phẩm chưa có đơn giá" });
                }
                var cartItem = new CartItem
                {
                    SoLuong = quantity,
                    Id = product.Id,
                    TenSP = product.TenSP,
                    DonGia = product.DonGia.Value,
                    Anh = product.Anh,
                };
                var cartCookie = _contextAccessor.HttpContext?.Request.Cookies["Cart"];
                Cart cart = new Cart();
                if (cartCookie != null)
                {
                    var cartData = cartCookie;
                    cart = JsonConvert.DeserializeObject<Cart>(cartData);
                }
                cart.AddItem(cartItem);
                SaveCart(cart);
                return Json(new { success = true, responseText = "Sản phẩm đã được thêm vào giỏ hàng" });
            }
            return Json(new { success = false, responseText = "Sản phẩm không tồn tại" });
        }
        private void SaveCart(Cart cart)
        {
            var cartData = JsonConvert.SerializeObject(cart);
            var cookieOptions = new CookieOptions
            {
                Expires = DateTimeOffset.Now.AddYears(1),
                HttpOnly = true,
                Secure = (bool)(_contextAccessor.HttpContext?.Request.IsHttps), 
                Path = "/"
            };
            _contextAccessor.HttpContext?.Response.Cookies.Append("Cart", cartData, cookieOptions);
        }
        public ActionResult RemoveFromCart(int productId)
        {
            var cart = GetCart();
            cart.RemoveItem(productId);
            SaveCart(cart);

            TempData["Message"] = "Sản phẩm đã được xóa khỏi giỏ hàng.";

            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult UpdateQuantity(int productId, int quantity)
        {
            var cart = GetCart();
            cart.UpdateItemQuantity(productId, quantity);
            SaveCart(cart);
            return Json(new { success = true, responseText = "Cập nhật số lượng thành công" });
        }

        [HttpGet]
        public int ItemCartCount()
        {
            var cart = GetCart(); 
            return cart.Items.Count();
        }
        
    }
}

E-commerce-23TH0024/ViewComponents/MenuViewComponent.cs
using E_commerce_23TH0024.Data;
using E_commerce_23TH0024.Models;
using E_commerce_23TH0024.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace E_commerce_23TH0024.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;
        private readonly MenuService _service;

        public MenuViewComponent(ApplicationDbContext context)
        {
            _context = context;
            _service = new MenuService(context);
        }

        public async Task<IViewComponentResult> InvokeAsync(string IdNhomMenu, string viewname)
        {
            if (IdNhomMenu == null)
                return Content("Menu ID is null");

            var menu = _service.GetMenus(IdNhomMenu);
            return View(viewname, menu);
        }
    }
}

E-commerce-23TH0024/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IN ẤN HỒNG LEN</title>
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="https://unpkg.com/aos@next/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/styles.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    @* @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery") *@
</head>
<body>
    <header class=" shadow-sm">
       
            <nav class="navbar navbar-expand-lg navbar-dark container py-2">
                <!-- Logo -->
                <a class="navbar-brand fw-bold" href="@Url.Action("Index", "Home")">
                    <img src="~/Images/logo.png" alt="Logo" class="logo" width="50" height="35"/>
                </a>
            <a href='@Url.Action("Index", "Cart_23TH0024")' class="icon-cart text-white position-relative me-2 shopping-cart">
                <i class="fas fa-shopping-cart fa-lg"></i>
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                    0
                </span>
            </a>
                <!-- Toggler button for mobile -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar"
                        aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Menu + Right Content -->
                <div class="collapse navbar-collapse justify-content-between" id="mainNavbar">
                    <!-- Main Menu -->
                    <div class="navbar-nav">
                        @await Component.InvokeAsync("Menu", new { IdNhomMenu = "main-menu", viewname = "MainMenu" })
                    </div>

                    <!-- Cart + Login -->
                    <div class="d-flex align-items-center gap-3">
                       
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        
    </header>


    <main>
        @RenderBody()
    </main>
    <footer>
        <div class="container align-content-center align-text-center">
            <p>CÔNG TY TNHH TMDV HỒNG LEN</p>
            <p>Điện thoại: 0904.844.382 - 094.760.9406</p>
            <p>Địa chỉ: 123 Củ Chi - Vĩnh Hải - Nha Trang</p>
            <p>© 2024 - 23TH0024</p>
        </div>
    </footer>
    <div id="loading" style="display:none;">
        <span>Đang tải...</span>
    </div>
   @*  @Scripts.Render("~/bundles/bootstrap") *@
    @RenderSection("scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script src="~/Scripts/CustomScript.js"></script>
    <script src="~/Scripts/jquery.signalR-2.4.3.min.js"></script>
    <script src="https://chatbot.inanhonglen.com/static/chat.js"></script>
    <script src="~/Scripts/jquery.signalR-2.4.3.min.js"></script>
    <script src="~/Scripts/custom_signalR.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var title = document.querySelectorAll(".title");
            title.forEach(function(el, i) {
                el.setAttribute("data-aos", "fade-up");
                el.setAttribute("data-aos-delay", i * 100);
            });

            var items = document.querySelectorAll(".product");
            items.forEach(function(el, i) {
                el.setAttribute("data-aos", "fade");
                el.setAttribute("data-aos-delay", i * 100);
            });
            AOS.init({
                duration: 800,
                once: true
            });
        });
    </script>
</body>

</html>